### ISSUE TITLE
How to tell what milestone the code is currently at?

### ISSUE THREAD

**Issue by jasonxeno** [LumaPictures/meteor-jquery-select2#2]
I enjoy you that you have a clear blueprint plan for the future, I was wondering how I can tell what milestone this package is currently at? For instance, I want to start using this package ASAP when it hits milestone 0.3 but I am not sure how I will tell when it hits that milestone or not. Perhaps it even did already, I'm not sure.

**Comment by jasonxeno** [comment]
My bad, I didn't understand the git hub milestone system. Now I do. Closing the issue.

**Comment by gjolund** [comment]
The milestones are just the version of the package.
